const express = require('express')
const app = express()
const port = 3000
const home = require('./routers/home')
app.use('/', home)
const user = require('./routers/user')
app.use('/', user)
const about = require('./routers/about')
app.use('/', about)
const contact = require('./routers/contact')
app.use('/', contact)
//app.listen(port)
app.listen(port, () => console.log(`Example app listening on port ${port}!`))